# Make backspace work
bind-key -n Bspace send-keys C-h

# C-b is not acceptable, vim uses it
set-option -g prefix C-a
bind-key C-a send-prefix

# Unbind default split keys
unbind '"'
unbind '%'

# Set the working directory of a new pane the same as of the current pane
bind '-' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"

# Forward focus events down to Vim
set -g focus-events on

# Show full True Color (24-bit color)
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc:Focus"

# Allow faster key repetition
set -s escape-time 10

# Increase history size
set-option -g history-limit 100000

# Vim-style pane movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"
